'use strict';
var path = require('path');
var lessConf = require("./tasks-config.js").less;
var fs = require('fs');

module.exports = function (grunt) {

    // Load grunt tasks from the tasks directory
    require('grunt-config-dir')(grunt, {
        configDir: path.resolve('grunt-tasks')
    });


    // Task to fix the cssMappURL generated by the less plugin
    grunt.registerTask('cssMappURL', function () {
        // Options
        var conf = require("./tasks-config.js").less;
        var find = "sourceMappingURL=public/compiled/maps/style.css.map";
        var replace = "sourceMappingURL=../maps/style.css.map";
        var cssFile = path.join(conf.output,"style.css");
        var data = grunt.file.read(cssFile);
        var x = data.replace(find, replace);
        grunt.file.write(cssFile, x);
        console.log('sourceMappingURL fixed in file: ' + cssFile);
    });


    grunt.registerTask("css",['less','autoprefixer',"cssmin"]);
    grunt.registerTask("js",['ts']);
    grunt.registerTask('default', ['imagemin', 'css','js' , "translate_extract"]);

};

